  version: '3'
  volumes:
    mariadb_volume:
      external: true
  services:
    mariadb:
      build: mariadb/
      hostname: mariadb
      networks:
        default:
          aliases:
            - mariadb
      environment:
        - MYSQL_ROOT_PASSWORD=dude_dont_do_that
        - MYSQL_DATABASE=binaryblob_ca
        - MYSQL_USER=project_manager
        - MYSQL_PASSWORD=production_is_super_secure
        - MYSQL_ALLOW_EMPTY_PASSWORD=no
        - MYSQL_RANDOM_ROOT_PASSWORD=yes
      volumes:
      - mariadb_volume:/var/lib/mysql

    daphne:
      build: .
      hostname: daphne
      networks:
        default:
          aliases:
            - daphne
      command: pipenv run daphne -e ssl:port=44433:privateKey=certs/dbserv.lan.key:certKey=certs/dbserv.lan.crt binaryblob_ca.asgi:application
      ports:
        - "443:44433/tcp"
      depends_on:
        - mariadb
        - redis
    redis:
      image: redis