  version: '3'
  networks:
    internal:
      driver: bridge
  volumes:
    mariadb_volume:
      external: true
    nginx_volume:
      external: true
  services:
    mariadb:
      build: mariadb/
      hostname: mariadb
      networks:
        - internal
      environment:
        - MYSQL_ROOT_PASSWORD=dude_dont_do_that
        - MYSQL_DATABASE=binaryblob_ca
        - MYSQL_USER=project_manager
        - MYSQL_PASSWORD=production_is_super_secure
        - MYSQL_ALLOW_EMPTY_PASSWORD=no
        - MYSQL_RANDOM_ROOT_PASSWORD=yes
      volumes:
      - mariadb_volume:/var/lib/mysql
    nginx:
      build: nginx/
      hostname: nginx
      networks:
        default:
          ports:
            - "443:443/tcp"
            - "80:80/tcp"
        - internal
      volumes:
        nginx_volume:/opt/site
    daphne:
      build: .
      hostname: daphne
      networks:
        - internal
      command: pipenv run daphne -p 44433 binaryblob_ca.asgi:application
      depends_on:
        - mariadb
        - redis
    redis:
      image: redis